repository:
  delete_branch_on_merge: true
  default_branch: main
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
      required_status_checks: null
      enforce_admins: null
      required_linear_history: null
      restrictions: null