name: Auto merge release bump PR

on:
  pull_request:
      types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
      types:
      - submitted
  check_suite: 
      types:
      - completed
  status: {}

jobs:

  automerge:
      runs-on: ubuntu-latest
      steps:
      - name: Automerging
        uses: pascalgn/automerge-action@v0.7.5
        #the actor that created pr
        if: github.actor == 'tzdevsa'
        env:
          GITHUB_TOKEN: "${{ secrets.API_TOKEN_GITHUB }}"
          GITHUB_LOGIN: tzdevsa
          MERGE_LABELS: ""
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "Auto merge push to all repositories."
          MERGE_RETRIES: "10"
          MERGE_RETRY_SLEEP: "10000"